# Generated by Django 2.2 on 2019-04-03 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_prospectexperience_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='prospectprofile',
            name='skills',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
