# Generated by Django 2.2 on 2019-04-04 01:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0004_userprofile_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='likes',
        ),
        migrations.AddField(
            model_name='prospectprofile',
            name='likes',
            field=models.ManyToManyField(related_name='likes', to=settings.AUTH_USER_MODEL),
        ),
    ]
